spring.application.name=ai-hub
server.port = 8080
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5.2
spring.devtools.restart.enabled=false

spring.ai.openai.embedding.options.model=mxbai-embed-large

spring.ai.openai.audio.speech.options.model=gpt-40-mini-tts
spring.ai.openai.audio.speech.options.voice=alloy
spring.ai.openai.audio.speech.options.response-format=mp3
spring.ai.openai.audio.speech.options.speed=1.2
